// The small bets, from research/small-bets-presence.md (P) and research/small-bets-direct.md (D), read 2026-10-05.
// Stage: 0 no users, 1 first users, 2 steady use, 3 newsworthy. Stages, minimums and stop signals are the notes'
// judgment calls unless a platform sets them. Order within a stage: cheapest first.

import type { Bet } from "./smallBets.js";

const S0 = "Stage 0: no users yet";
const S1 = "Stage 1: the first users";
const S2 = "Stage 2: steady use";
const S3 = "Stage 3: something newsworthy";

export const BETS: Bet[] = [
  // ── Stage 0 ─────────────────────────────────────────────────────────────
  {
    id: "listings",
    effortHours: 3,
    ceiling: "capped",
    name: "List it where people already look",
    what: "Free listings in app stores, developer registries (MCP Registry, GitHub Marketplace, VS Code, Chrome Web Store, package registries), integration directories and curated lists.",
    stage: 0,
    cost: "Free; 1–4 hours per listing. Gated directories (Slack, paid GitHub apps, Discord) need users first.",
    judgeAfter: "90 days",
    measure: "Tagged links from each listing; a 'how did you hear about us' answer",
    stop: "A handful of tagged visits and no 'heard about us' mentions after 90 days, with a complete listing. Keep free listings that cost nothing to maintain.",
    evidence: "some",
    section: S0,
  },
  {
    id: "answer-questions",
    effortHours: 32,
    ceiling: "steady",
    name: "Answer where the problem is already discussed",
    what: "Answer questions on Stack Overflow, Reddit, Discord servers, forums and nearby projects' GitHub issues, linking only when the link answers the question.",
    stage: 0,
    needs: { expertise: true },
    cost: "Free; 3–5 hours a week",
    judgeAfter: "8–12 weeks",
    measure: "Tagged links in answers; sign-ups that name the place",
    stop: "No clicks or sign-ups from answers after 12 weeks, or moderators object.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "comparison-pages",
    effortHours: 10,
    ceiling: "steady",
    name: "Comparison and 'alternative to X' pages",
    what: "Honest pages comparing you with known rivals, and help docs written as answers to search queries.",
    stage: 0,
    cost: "2–4 hours per page",
    judgeAfter: "2–3 months in Search Console",
    measure: "Impressions, clicks and sign-ups per page",
    stop: "Impressions but no clicks after 3 months: rewrite the title; clicks but no sign-ups: rewrite the page. Drop only if the query has no volume.",
    evidence: "some",
    section: S0,
  },
  {
    id: "error-pages",
    effortHours: 15,
    ceiling: "steady",
    name: "One page per painful error message",
    what: "A page titled with the exact error text, explaining the cause and the fix.",
    stage: 0,
    needs: { expertise: true },
    audiences: ["developers", "businesses"],
    cost: "1–2 hours per page",
    judgeAfter: "About 3 months in Search Console",
    measure: "Search clicks per page, then clicks through to the product",
    stop: "Clicks but no product clicks after 3 months: keep as support content, stop writing new ones for acquisition.",
    evidence: "some",
    section: S0,
  },
  {
    id: "teardowns",
    effortHours: 24,
    ceiling: "lopsided",
    tries: 2,
    name: "Teardowns of well-known things",
    what: "Apply your method or tool to something famous and publish what you found.",
    stage: 0,
    needs: { expertise: true },
    cost: "2–5 days per teardown",
    judgeAfter: "2–6 weeks after publishing",
    measure: "Links, mentions, community traction, sign-ups from the post",
    stop: "Two teardowns with no traction or links: pick better-known targets or sharper findings.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "free-tool",
    effortHours: 40,
    ceiling: "lopsided",
    name: "A free tool or calculator",
    what: "A small standalone tool that solves one narrow, searchable problem and links to the product.",
    stage: 0,
    cost: "1–10 days to build; cheap hosting",
    judgeAfter: "2–3 months of indexing, or 2 weeks after a community launch",
    measure: "Uses a week and click-through to the product",
    stop: "Under a few dozen uses a week, or almost no click-through, after 3 months. Try one rewrite of the tool's page first.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "one-command-try",
    effortHours: 24,
    ceiling: "capped",
    name: "A one-command try with no sign-up",
    what: "An npx, pipx or docker one-shot that gives a result on the user's own input and prints a link.",
    stage: 0,
    audiences: ["developers"],
    surfaces: ["cli", "library", "api"],
    cost: "1–5 days to package",
    judgeAfter: "4–8 weeks",
    measure: "Downloads and clicks on the printed link",
    stop: "Downloads with almost no clicks on the link after 8 weeks: change what the output shows before giving up.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "open-source",
    effortHours: 60,
    ceiling: "lopsided",
    name: "Open-source a useful piece",
    what: "Publish a CLI, GitHub Action, library or dataset that is useful without the paid product, with a README that works as a landing page.",
    stage: 0,
    needs: { expertise: true },
    audiences: ["developers"],
    involves: ["open-sourcing-code"],
    cost: "Days to weeks, plus issue triage",
    judgeAfter: "3–6 months",
    measure: "Tagged README clicks and sign-ups that mention the repo (stars correlate weakly with use)",
    stop: "Stars but no README clicks or sign-ups after 3–6 months: keep it public if upkeep is cheap, stop launch effort.",
    evidence: "some",
    section: S0,
  },
  {
    id: "upstream-fixes",
    effortHours: 10,
    ceiling: "capped",
    name: "Fix things in projects your users use",
    what: "Pull requests and docs fixes to nearby open-source projects, for credibility rather than promotion.",
    stage: 0,
    needs: { expertise: true },
    audiences: ["developers"],
    cost: "Hours per pull request",
    judgeAfter: "3 months",
    measure: "Profile and site visits from those projects; maintainers who reply or mention you",
    stop: "No visits or relationships after 3 months.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "fix-famous-projects",
    effortHours: 24,
    ceiling: "lopsided",
    tries: 3,
    name: "Fix what your tool finds in well-known open-source projects",
    what: "Run your product on a popular open-source project under realistic load (seed data, simulated traffic), confirm one real problem by hand, and send a pull request with the fix, a reproduction and before/after numbers.",
    stage: 0,
    needs: { expertise: true },
    audiences: ["developers"],
    cost: "Free; about 2–4 days per project",
    judgeAfter: "3 projects, then 4–8 weeks for reviews and any write-up",
    measure: "PRs merged; maintainers who reply; visits and sign-ups from the PR and from a write-up of the finding",
    stop: "None of 3 well-prepared PRs is merged or answered: pick projects whose maintainers welcome performance work, or write the finding up as a teardown instead.",
    evidence: "some",
    section: "Stage 0: no users yet",
  },
  {
    id: "moderator-tool",
    effortHours: 24,
    ceiling: "lopsided",
    name: "A tool for the community's moderators",
    what: "Build a small bot or tool that solves a known pain for the moderators of a community where your users gather.",
    stage: 0,
    needs: { communities: true },
    audiences: ["hobbyists", "developers", "consumers"],
    cost: "Days to build, then upkeep",
    judgeAfter: "2 months",
    measure: "Communities that adopt it; mentions and visits from them",
    stop: "No community adopts it after 2 months of offering it.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "social-presence",
    effortHours: 36,
    ceiling: "lopsided",
    tries: 24,
    name: "Post regularly as the founder",
    what: "A founder account on the one platform where buyers already talk, posting findings and the build at least twice a week.",
    stage: 0,
    cost: "2–5 hours a week",
    judgeAfter: "8–12 weeks of steady posting",
    measure: "Conversations with buyer-type people; sign-ups that name the platform",
    stop: "After 12 weeks at 2+ posts a week, no buyer conversations and no sign-ups from it: change platform or format before dropping social.",
    evidence: "some",
    section: S0,
  },
  {
    id: "founder-videos",
    effortHours: 10,
    ceiling: "lopsided",
    ceilingFor: { businesses: "capped", developers: "capped" },
    tries: 20,
    name: "Short videos of the product doing its job",
    what: "Founder-made 15–60 second videos showing one result, posted on the short-video platform the audience uses.",
    stage: 0,
    involves: ["founder-on-camera"],
    cost: "A phone and about 30 minutes a video",
    judgeAfter: "A fixed number of posts set in advance (for example 20)",
    measure: "Views to installs or sign-ups per video, with a link per platform",
    stop: "No format gets copied or brings sign-ups after the set number of posts.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "pinterest-pins",
    effortHours: 10,
    ceiling: "steady",
    name: "Pin the work people make on Pinterest",
    what: "Post images of finished projects (from your gallery, with makers' permission) as pins with a plain title and description that link back, starting before the season's searches rise.",
    stage: 0,
    audiences: ["consumers", "hobbyists"],
    cost: "Free; about 30 minutes a pin; 2:3 images",
    judgeAfter: "20 pins, then 2–3 months (pins keep getting found)",
    measure: "Saves and outbound clicks per pin in Pinterest analytics (claim your site); sign-ups from Pinterest",
    stop: "After 20 pins and 3 months, almost no saves or clicks: the audience isn't on Pinterest, or the images don't show the result.",
    evidence: "some",
    section: "Stage 0: no users yet",
  },
  {
    id: "cold-one-to-one",
    effortHours: 20,
    ceiling: "capped",
    name: "Personal messages to clearly fitting people",
    what: "Research 20–50 people who visibly have the problem (public issues, posts, job ads) and write to each one personally.",
    stage: 0,
    involves: ["cold-outreach"],
    cost: "Free; 15–30 minutes per message",
    judgeAfter: "30–50 messages",
    measure: "Replies, calls booked, sign-ups",
    stop: "No replies that lead anywhere after 50 messages: change the list or the offer. Never use emails scraped from GitHub (its rules forbid it).",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "own-data-report",
    effortHours: 40,
    ceiling: "lopsided",
    tries: 2,
    name: "Publish your own data",
    what: "A report, index or benchmark from data nobody else has published, including public data you collected and organised.",
    stage: 2,
    dataSkipsStage: true,
    needs: { data: true },
    cost: "2–10 days per report, plus pitching",
    judgeAfter: "4–8 weeks after release",
    measure: "New referring domains, mentions, press",
    stop: "Two reports in a row each earn fewer than about 5 new referring domains and no press: change the topic or move to a small recurring index.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "data-pages",
    effortHours: 24,
    ceiling: "steady",
    name: "Public pages built from your data",
    what: "One indexable page per item, error or record, each with something unique and useful on it.",
    stage: 2,
    dataSkipsStage: true,
    needs: { data: true },
    cost: "Days to build templates",
    judgeAfter: "About 3 months in Search Console",
    measure: "Indexed pages, impressions, clicks",
    stop: "Most pages 'crawled, not indexed' or without impressions after 3 months: cut to the pages with real content rather than adding more.",
    evidence: "some",
    section: S0,
  },
  {
    id: "weekly-digest",
    effortHours: 16,
    ceiling: "steady",
    name: "A weekly digest generated from your data",
    what: "An automated weekly summary posted where the audience is, with the community's permission.",
    stage: 2,
    dataSkipsStage: true,
    needs: { data: true },
    cost: "1–3 days to automate",
    judgeAfter: "6–8 weekly issues",
    measure: "Clicks per issue; follows or subscriptions",
    stop: "Clicks fall for 4 weeks in a row, or moderators object.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "waitlist-referral",
    effortHours: 16,
    ceiling: "lopsided",
    name: "A waitlist where referrals move people up",
    what: "A pre-launch sign-up where each person gets a link, and referrals move them up the line or earn a reward.",
    stage: 0,
    launch: "before",
    cost: "A page and a tool; days",
    judgeAfter: "2–4 weeks",
    measure: "Sign-ups per referrer; share of sign-ups that came by referral",
    stop: "Almost no one shares their link after 2–4 weeks.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "integration",
    effortHours: 80,
    ceiling: "steady",
    name: "An integration or plugin inside another product",
    what: "A bot, plugin or CI integration that does a clear job inside a platform your users already use.",
    stage: 0,
    surfaces: ["web-app", "api", "bot", "cli", "library"],
    cost: "1–4 weeks per integration, plus upkeep when the host changes",
    judgeAfter: "2–3 months",
    measure: "Installs, and installs that become active accounts",
    stop: "Installs but almost no active accounts after 3 months, or upkeep costs more than the sign-ups justify.",
    evidence: "some",
    section: S0,
  },

  // ── Stage 1 ─────────────────────────────────────────────────────────────
  {
    id: "merchant-visits",
    effortHours: 20,
    ceiling: "steady",
    name: "Sign up merchants in person, one street at a time",
    what: "Visit the independent shops on one street or neighbourhood with a ready-made listing to approve, and sign the ones that agree; list only merchants who said yes.",
    stage: 0,
    audiences: ["local"],
    cost: "Free; about an hour per visit, including follow-up",
    judgeAfter: "20 visits",
    measure: "Merchants signed per visit; signed merchants still active after a month",
    stop: "Fewer than about 1 in 10 visits sign: change the offer (price, setup work, what the merchant gets) before visiting more. Never list a business that hasn't agreed: the FTC made a delivery platform pay $25M for listing up to 325,000 restaurants without consent.",
    evidence: "anecdote",
    section: "Stage 0: no users yet",
  },
  {
    id: "in-store-signs",
    effortHours: 4,
    ceiling: "steady",
    name: "Signs and QR codes in partner shops",
    what: "Give each signed merchant a counter sign or table tent with a QR code to your app or page, tagged per shop.",
    stage: 1,
    audiences: ["local"],
    cost: "Printing; minutes per shop",
    judgeAfter: "4 weeks per shop",
    measure: "Scans and sign-ups per shop (one tagged link or code per shop)",
    stop: "Signs in a shop bring almost no scans in 4 weeks: move them to where people wait (the till, the pickup counter) or drop them there.",
    evidence: "anecdote",
    section: "Stage 1: the first users",
  },
  {
    id: "founder-emails",
    effortHours: 5,
    ceiling: "steady",
    name: "Email every new sign-up, payer and canceller yourself",
    what: "A short plain-text email from the founder to each new user asking what they hoped to do, and to each canceller asking why.",
    stage: 1,
    needs: { accounts: true },
    cost: "Free; 5–10 minutes per email plus replies",
    judgeAfter: "20–30 emails or 4 weeks",
    measure: "Reply rate; what replies teach; activation of users who got one",
    stop: "Replies stop teaching anything new; keep it for payers and cancellers.",
    evidence: "some",
    section: S1,
  },
  {
    id: "onboarding-calls",
    effortHours: 10,
    ceiling: "steady",
    name: "Onboarding calls and free audits",
    what: "Offer new users a short setup call, or offer a free review of the prospect's own problem.",
    stage: 1,
    needs: { expertise: true },
    cost: "Free; 30–60 minutes per call plus preparation",
    judgeAfter: "10 calls",
    measure: "Calls booked; activation and retention of users who had one",
    stop: "After 10 calls, no difference in activation and nothing new learned.",
    evidence: "some",
    section: S1,
  },
  {
    id: "ask-happy-users",
    effortHours: 2,
    ceiling: "capped",
    name: "Ask happy users for an introduction, a review or a quote",
    what: "Right after a success moment, ask for one introduction, a review or a testimonial. Ask every customer for reviews, not only happy ones (Google's rule).",
    stage: 1,
    cost: "Free; minutes per ask",
    judgeAfter: "20 asks",
    measure: "Introductions, reviews and quotes per ask",
    stop: "Fewer than a few yeses in 20 asks: change the moment or the ask.",
    evidence: "some",
    section: S1,
  },
  {
    id: "launch-sites",
    effortHours: 16,
    ceiling: "lopsided",
    name: "One launch-site post",
    what: "Product Hunt, Show HN, a fitting subreddit or BetaList, with a working product people can try now.",
    stage: 0,
    launch: "after",
    cost: "Mostly free; 1–2 days of preparation and a day of replies",
    judgeAfter: "1 week",
    measure: "Sign-ups through a tagged link; retained users a month later",
    stop: "A spike with no retained users: the product, not the channel, needs work.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "changelog",
    effortHours: 4,
    ceiling: "capped",
    name: "A public changelog and 'what's new' emails",
    what: "A dated page of what changed, and short update emails to opted-in users.",
    stage: 1,
    cost: "30–60 minutes per release",
    judgeAfter: "2–4 weeks after each email",
    measure: "Reactivation of lapsed users against a held-out group",
    stop: "Two or three emails reactivate no more than the held-out group: keep the page, cut the email.",
    evidence: "anecdote",
    section: S1,
  },
  {
    id: "curator-submissions",
    effortHours: 1,
    ceiling: "lopsided",
    tries: 10,
    name: "Send something useful to niche newsletters",
    what: "Submit a useful post or tool to the 'tools' or 'links' sections of newsletters your audience reads.",
    stage: 0,
    launch: "after",
    cost: "Free; minutes each",
    judgeAfter: "Per issue",
    measure: "Tagged clicks and sign-ups per mention",
    stop: "Several mentions with no clicks: send better posts rather than the product page.",
    evidence: "anecdote",
    section: S0,
  },
  {
    id: "guest-spots",
    effortHours: 24,
    ceiling: "steady",
    name: "Podcasts, meetups and guest posts",
    what: "Appear on small podcasts and local meetups, or write for someone else's newsletter or blog.",
    stage: 1,
    needs: { expertise: true },
    cost: "Free (travel for talks); 3–10 hours each",
    judgeAfter: "3–5 appearances",
    measure: "Tagged links or a code per appearance; 'heard about us' answers",
    stop: "No sign-ups traceable after 5 appearances.",
    evidence: "anecdote",
    section: S1,
  },
  {
    id: "journalist-requests",
    effortHours: 10,
    ceiling: "lopsided",
    name: "Answer journalists' source requests",
    what: "Reply quickly to reporters asking for expert sources on matching sites.",
    stage: 1,
    needs: { expertise: true },
    cost: "Free or small subscription; minutes per reply",
    judgeAfter: "2–3 months",
    measure: "Quotes published; links and visits from them",
    stop: "No quotes after 3 months, or quotes that bring no visits (common for unknown products).",
    evidence: "anecdote",
    section: S1,
  },
  {
    id: "calendar-events",
    effortHours: 12,
    ceiling: "lopsided",
    tries: 2,
    name: "Show up on the audience's calendar",
    what: "Have something ready for the dates that matter to your audience: a season reset, a framework release, a conference week, a holiday.",
    stage: 1,
    seasonSkipsStage: true,
    cost: "Free; 5–20 hours of preparation",
    judgeAfter: "After the event, against the same window without it",
    measure: "Visits and sign-ups in the event window against a normal window",
    stop: "No lift over a normal week for two events.",
    evidence: "anecdote",
    section: S1,
  },
  {
    id: "browser-extension",
    effortHours: 80,
    ceiling: "steady",
    name: "A browser extension on the sites your audience uses",
    what: "An extension that adds your data or feature to a site your audience already visits often.",
    stage: 1,
    surfaces: ["web-app", "website", "browser-extension", "api"],
    cost: "1–3 weeks, plus upkeep when the host site changes",
    judgeAfter: "2 months",
    measure: "Installs, weekly active users, uninstalls",
    stop: "Uninstalls approach installs, or upkeep costs more time than its users justify.",
    evidence: "anecdote",
    section: S1,
  },
  {
    id: "small-sponsorship",
    effortHours: 2,
    ceiling: "capped",
    name: "Sponsor something small the audience cares about",
    what: "Pay tens to hundreds of dollars to sponsor a community event, tournament or open-source maintainer.",
    stage: 1,
    budgetSkipsStage: 100,
    needs: { budget: 50 },
    involves: ["paid-promotion"],
    cost: "Tens to hundreds of dollars; little time",
    judgeAfter: "Per event",
    measure: "Tagged visits and sign-ups per sponsorship",
    stop: "Two sponsorships with no traceable sign-ups.",
    evidence: "anecdote",
    section: S1,
  },
  {
    id: "founder-thanks",
    effortHours: 3,
    ceiling: "capped",
    name: "Thank the first users personally",
    what: "A personal note or short video to each early user. Research found no effect on later behaviour, so do it because it's right, not as growth.",
    stage: 1,
    needs: { accounts: true },
    cost: "Minutes each",
    judgeAfter: "n/a",
    measure: "Replies",
    stop: "Don't count on it for growth.",
    evidence: "some",
    section: S1,
  },
  {
    id: "hiring-post",
    effortHours: 1,
    ceiling: "capped",
    name: "A hiring post that explains the product",
    what: "A post in a hiring thread (for example HN's monthly 'Who is hiring') that describes what you build. Only with a real open role.",
    stage: 1,
    audiences: ["developers", "businesses"],
    cost: "Free; an hour",
    judgeAfter: "1 month",
    measure: "Visits and sign-ups from the post",
    stop: "Post only when hiring.",
    evidence: "anecdote",
    section: S1,
  },

  // ── Stage 2 ─────────────────────────────────────────────────────────────
  {
    id: "shareable-outputs",
    effortHours: 24,
    ceiling: "lopsided",
    name: "Outputs people want to share",
    what: "A share link or image card for the results users are proud of or surprised by.",
    stage: 2,
    cost: "1–5 days to build",
    judgeAfter: "4–8 weeks of normal use",
    measure: "Share rate per result; sign-ups from shared pages",
    stop: "Fewer than about 1 in 50 results shared, or no sign-ups from shares after 8 weeks.",
    evidence: "anecdote",
    section: S2,
  },
  {
    id: "embeds",
    effortHours: 24,
    ceiling: "steady",
    name: "Embeddable widgets that link back",
    what: "A widget, tooltip or badge other sites embed, with a link back (Google says to nofollow links in distributed widgets).",
    stage: 1,
    cost: "Days to build",
    judgeAfter: "2–3 months",
    measure: "Sites embedding it; visits from embeds",
    stop: "Few sites embed it after 3 months.",
    evidence: "anecdote",
    section: S1,
  },
  {
    id: "building-in-public",
    effortHours: 18,
    ceiling: "lopsided",
    tries: 12,
    name: "Build in public",
    what: "Share progress, decisions and numbers openly as you go.",
    stage: 1,
    involves: ["sharing-metrics"],
    audiences: ["developers", "businesses"],
    cost: "1–2 hours a week",
    judgeAfter: "3 months",
    measure: "Followers who are buyers (not other founders); sign-ups that name it",
    stop: "The audience grows but no customers come from it after 3 months, or a competitor copies what you disclosed.",
    evidence: "anecdote",
    section: S1,
  },
  {
    id: "co-marketing",
    effortHours: 20,
    ceiling: "steady",
    name: "Co-marketing with an adjacent tool or creator",
    what: "A joint post, integration launch or webinar with a product or creator serving the same people.",
    stage: 2,
    cost: "Free to small; 10–30 hours per project",
    judgeAfter: "Per project",
    measure: "Sign-ups from the partner's audience",
    stop: "A project that brings nothing: pick a partner with more overlap.",
    evidence: "anecdote",
    section: S2,
  },
  {
    id: "own-community",
    effortHours: 36,
    ceiling: "steady",
    name: "Your own community or newsletter",
    what: "A Discord or Slack for users, or a newsletter, once people already talk to you.",
    stage: 2,
    cost: "Mostly free tools; 2–5 hours a week, ongoing",
    judgeAfter: "3 months",
    measure: "Weekly active members; retention of members against non-members",
    stop: "A room that stays empty after 3 months hurts more than none: close it.",
    evidence: "some",
    section: S2,
  },
  {
    id: "newsletter-sponsorship",
    effortHours: 3,
    ceiling: "capped",
    tries: 3,
    name: "Sponsor a niche newsletter",
    what: "Buy a slot in a newsletter your audience reads.",
    stage: 2,
    budgetSkipsStage: 300,
    needs: { budget: 100 },
    involves: ["paid-promotion"],
    cost: "From about $10 for a classified to $1,500 per issue",
    judgeAfter: "2–3 slots (one is noise)",
    measure: "Tagged clicks, sign-ups and retained users per slot",
    stop: "Cost per retained user above what a user is worth after 3 slots.",
    evidence: "anecdote",
    section: S2,
  },
  {
    id: "paid-tutorial",
    effortHours: 2,
    ceiling: "steady",
    tries: 2,
    name: "Pay a user to write a tutorial",
    what: "Commission a real user to write about solving a problem with your product.",
    stage: 2,
    budgetSkipsStage: 400,
    needs: { budget: 300 },
    involves: ["paid-promotion"],
    cost: "About $300–$400 per technical tutorial",
    judgeAfter: "Per article",
    measure: "Visits, links and sign-ups per article",
    stop: "Two articles that bring nothing.",
    evidence: "anecdote",
    section: S2,
  },
  {
    id: "affiliate",
    effortHours: 10,
    ceiling: "steady",
    name: "An affiliate or referral link with a commission",
    what: "A link that pays users or creators a share of the sales they bring.",
    stage: 2,
    needs: { revenue: true },
    cost: "Commission plus tool fees",
    judgeAfter: "3 months",
    measure: "Sales per affiliate; refunds",
    stop: "Few active affiliates after 3 months, or sales that would have happened anyway.",
    evidence: "anecdote",
    section: S2,
  },
  {
    id: "perk-programmes",
    effortHours: 6,
    ceiling: "capped",
    name: "Startup and student perk listings",
    what: "Offer credits or a free tier through startup perk catalogues and student developer bundles.",
    stage: 2,
    audiences: ["developers", "businesses"],
    cost: "Hours to apply, plus the cost of the perks",
    judgeAfter: "After the perk period",
    measure: "Redemptions, activation, conversion after the perk",
    stop: "Redemptions with almost no activation, or no one converts after the perk.",
    evidence: "anecdote",
    section: S2,
  },
  {
    id: "lifetime-deal",
    effortHours: 10,
    ceiling: "capped",
    name: "A lifetime deal on a deal site",
    what: "Sell lifetime access for a one-time price. Brings cash and users who expect support forever; often the wrong customers.",
    stage: 2,
    needs: { revenue: true },
    audiences: ["businesses"],
    involves: ["discounts"],
    cost: "Revenue share with the site, plus future support",
    judgeAfter: "The deal window, then 6 months of support load",
    measure: "Buyers who stay active; support hours per buyer",
    stop: "Run once at most; stop if support load outgrows the cash.",
    evidence: "anecdote",
    section: S2,
  },

  // ── Stage 3 ─────────────────────────────────────────────────────────────
  {
    id: "press",
    effortHours: 20,
    ceiling: "lopsided",
    name: "Pitch the press",
    what: "Pitch a story with numbers or a finding that others would retell.",
    stage: 3,
    needs: { newsworthy: true },
    cost: "Free; days of pitching",
    judgeAfter: "2–4 weeks",
    measure: "Coverage, links, sign-ups from coverage",
    stop: "No pickup from 20 targeted pitches: the story isn't there yet.",
    evidence: "anecdote",
    section: S3,
  },
];
